easy_admin:
    design:
        menu:
            - { entity: 'User', icon: 'user'}
            - { entity: 'Department', icon: 'briefcase'}
            - { entity: 'Event', icon: 'users'}
            - { entity: 'Edition', icon: 'calendar-o'}
            - { label: 'Inicio', icon: 'home', url: '/', rel: 'index' }